export const GET_PCS_BY_COTEGORY_START = 'GET_PCS_BY_COTEGORY_START';
export const GET_PCS_BY_COTEGORY_SUCCESS = 'GET_PCS_BY_COTEGORY_SUCCESS';
export const GET_PCS_BY_COTEGORY_FAILURE = 'GET_PCS_BY_COTEGORY_FAILURE';