export const GET_PCS_BY_COTEGORY_START = 'GET_PCS_BY_COTEGORY_START';
export const GET_PCS_BY_COTEGORY_SUCCESS = 'GET_PCS_BY_COTEGORY_SUCCESS';
export const GET_PCS_BY_COTEGORY_FAILURE = 'GET_PCS_BY_COTEGORY_FAILURE';

export const SET_DEFAULT_STATUSES = 'SET_DEFAULT_STATUSES';
export const SET_RESPONSE_SUCCESS_STATUSES = 'SET_RESPONSE_SUCCESS_STATUSES';
export const SET_RESPONSE_FAILURE_STATUSES = 'SET_RESPONSE_FAILURE_STATUSES';