export const SET_PC_TO_CART_START = 'SET_PC_TO_CART_START';
export const SET_PC_TO_CART_SUCCESS = 'SET_PC_TO_CART_SUCCESS';
export const SET_PC_TO_CART_FAILURE = 'SET_PC_TO_CART_FAILURE';

export const DELET_PC_FROM_CART_START = 'DELET_PC_FROM_CART_START';
